### ISSUE TITLE
Libgdx-natives and libgdx clearly derrived from upstream, does not retain LICENSE file

### ISSUE THREAD

**Issue by badlogic** [bugvm/bugvm-bindings#4]
https://github.com/libgdx/libgdx

Relicensing under GPL 3 as done with root folder LICENSE file is a no go. Distribution of GPL on iOS is a no go. Fix this.

You may also look into licensing issue of the other code bits copied. Essentially duplicates of this issue.

**Comment by bugvm** [comment]
fixed
